import type { Metadata, Viewport } from "next";
import { Fraunces, Space_Grotesk } from "next/font/google";
import "./globals.css";

// Fraunces — the literary "memory" voice (wordmark, headers, italic notes).
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
  style: ["normal", "italic"],
});

// Space Grotesk — the interface voice (titles, labels, data).
const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
  display: "swap",
});

// iOS launch images — the two phone sizes the phone app is designed against
// (spec §7), generated by scripts/gen-icons.mjs. Without these, a home-screen
// install flashes WHITE while it boots, at an app whose whole palette is dusk.
// The media queries are Apple's device-width/height/pixel-ratio form; a device
// that matches nothing here simply gets no launch image, which is the old
// behaviour, not a broken one.
const STARTUP_IMAGES = [
  {
    url: "/icon-splash-1125x2436.png",
    media:
      "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)",
  },
  {
    url: "/icon-splash-1290x2796.png",
    media:
      "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
  },
];

export const metadata: Metadata = {
  title: "Working Memory",
  description: "What's on your mind — now, and everything it used to be.",
  // The iOS home-screen install IS the phone app's runtime (spec §7/§1.9):
  // standalone chrome, no Safari toolbars, safe areas we control. Safari in a
  // tab still works — it's the fallback, not the target.
  //
  // `black-translucent` means the status bar draws OVER the page, which is only
  // safe because the phone shell pads by env(safe-area-inset-top) and the
  // viewport below is `viewport-fit: cover`. The two go together; changing one
  // without the other puts the clock on top of the board.
  appleWebApp: {
    capable: true,
    title: "Working Memory",
    statusBarStyle: "black-translucent",
    startupImage: STARTUP_IMAGES,
  },
  // apple-touch-icon comes from app/apple-icon.png (180×180, full-bleed) and
  // the manifest from app/manifest.ts — Next emits the <link>s for both.
};

// A single colour, not a light/dark media pair: the app renders dark whatever
// the device prefers unless "light" was explicitly stored (see THEME_INIT).
//
// ADD keys here, never replace the object wholesale — Next merges only what's
// supplied, so an incomplete viewport export silently drops the theme colour.
// `viewportFit: 'cover'` is what lets the phone tab bar reach the bottom edge
// and makes env(safe-area-inset-*) return anything but 0 (spec §7, §9).
export const viewport: Viewport = {
  themeColor: "#0b0e1a",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// Applies the saved theme before anything paints (inline + synchronous at the
// top of <body>, so there's no dark→light flash). Dark is the default; only
// "light" is ever stored. Keep in sync with components/ThemeToggle.tsx.
const THEME_INIT = `try{if(localStorage.getItem("wm-theme")==="light")document.documentElement.dataset.theme="light"}catch(e){}`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${grotesk.variable}`}
      suppressHydrationWarning
    >
      <body>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT }} />
        {children}
      </body>
    </html>
  );
}
