import type { MetadataRoute } from "next";

// Served at /manifest.webmanifest; Next injects the <link rel="manifest">.
// Icons are generated by scripts/gen-icons.mjs (`npm run icons`).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Working Memory",
    // Android truncates the home-screen label around 12 characters, which
    // would clip "Working Memory" mid-word.
    short_name: "Memory",
    description: "What's on your mind — now, and everything it used to be.",
    start_url: "/",
    display: "standalone",
    // Dark is the app's default regardless of device preference (only an
    // explicit "light" is ever stored — see THEME_INIT in app/layout.tsx), so
    // the splash and chrome match --bg-0.
    background_color: "#0b0e1a",
    theme_color: "#0b0e1a",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
